### ISSUE TITLE
Downgrade Amazon to "Hard"

### ISSUE THREAD

**Issue by meeDamian** [justgetmydata/jgmd#57]
While **requesting** the data is not too difficult, actually **retrieving** it is made as difficult as possible: in my case I got 177 microscopic files, each one needed to be individually clicked.  For more details see: https://twitter.com/meeDamian/status/1446384769969893398?s=20

**Comment by daviddavo** [comment]
Some of them are not even 1k in size!

Feel free to update it and do a PR if you want. You should only have to edit the [_data/sites.json](https://github.com/justgetmydata/jgmd/blob/master/_data/sites.json) file

**Comment by meeDamian** [comment]
Done.  I left spanish as-is, as _no habla espanol_ 😬, and didn't want to add butchered automatic translation.
